### ISSUE TITLE
What are plans for support CodeSniffer 3?

### ISSUE THREAD

**Issue by TomasVotruba** [hostnet/phpcs-tool#14]
Hey, I like few sniffs of yours. Thanks for making them, great work!

But I'm using CodeSniffer 3 (relased [yesterday](https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.0.0)) and I wonder, if you plan to support it.

I can help with upgrade if you need.

**Comment by hboomsma** [comment]
Hey thnx for the heads-up. We are definitely going​ to support version 3. Your help would be great. I did not look into version 3 yet, but I imagine upgrading not to hard. BC is not needed as we only interface with the tool using cli.

**Comment by TomasVotruba** [comment]
Awesome! Thanks for reply. There are some easy changes and some coupled ones, depends on your code.
So shall I prepare PR?

**Comment by hboomsma** [comment]
I would welcome that.

**Comment by mdeheij** [comment]
Fixed in PR #16
