### ISSUE TITLE
Missing README with sniff overview

### ISSUE THREAD

**Issue by TomasVotruba** [hostnet/phpcs-tool#17]
Hey, I really like few sniffs in here and I think of usign them. But I don't want to open manually every sniff file and decode, what the function is.

Do you plan to add a README with their overview? 
[Somehting like this](https://github.com/Symplify/CodingStandard#rules-overview)

I think that would be worth it for other people, since you've got over 42 releases.

Great job :tada:

**Comment by hboomsma** [comment]
Hi @TomasVotruba,

great idea. I'll look into it, but your help will be highly appreciated.

**Comment by TomasVotruba** [comment]
That would be great.
I'm quite full with my open-source projects and I don't know more than 2 sniffs in here. That's why I need a Readme.

I can help you with styling the examples and Readme. Just  put in the names of a sniff and no/yes examples
